### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by ThreepE0** [sdatkinson/neural-amp-modeler#1]
Hello,
Thanks for sharing this project!  I'm very eager to get training and testing this out, but I'm a bit of a newb and am running into a Tensorflow 2 compatibility issue (Session isn't available in Tensorflow 2.)  I'm attempting to stumble through converting the code to the new eager format, but I have no idea what I'm doing.  Have you converted this to Tensorflow 2, or would you be willing to update?

**Comment by sdatkinson** [comment]
Hi, @ThreepE0!

In short, this code is unfortunately pretty old at this point. Looking back at TF's releases, I bet I was using TF 1.12 back when I last worked on this. Best bet would be to dig that up (and the associated CUDA/cuDNN versions) to resurrect this.

As far as a refresh, frankly if anything it'd be PyTorch as I find it all around a better solution at this point for general deep learning...TF was just a good-enough option back when this was actively being worked on and isn't something I'd stick with across the TF1/TF2 break.

**Comment by ThreepE0** [comment]
Thanks for the reply!  I got it running using the tensorflow migration tool and by importing tf-slim for layers, and the results are so much better than the other models I've tried so far.  Of course, let me know if I should share the changes that got things working, if you're at all interested.  I'm trying to keep in mind that I'm just using your supplied data, as I'm not 100% sure how to take my own wavs and dump them to a numpy file just yet (not sure if they should be 24 bit/44.1, what else needs to be done if anything, etc...)

But as you mentioned, the code is old and maybe I should focus on learning the concepts and trying to come up with something from scratch rather than spending too much time fidgeting with the existing code...

I'll try and pick through and figure out why your method seems to hone in on a reasonable result soooo much faster than PedalnetRT here on github for example (using pytorch_lightning.)  I know this is just about the least technical description I could come up with, but running your model for about 10k minibatches finishes in just a couple of minutes.  If I run the PedalNetRt model for 90k Epochs, it runs for about 10 hours, and the results are about on par with your model here, but in some ways even less impressive (missing/rounded transients, etc...)

I liked the explanation of the logic in your word-press article, and I think the approach you outlined will help me figure things out to a degree... I'm struggling because I don't know Python very well, nor am I a machine learning expert.  Trying to get up to speed with all of these things has been challenging, but fun.

Any tips or reading material you suggest would be appreciated;  It seems most of the machine learning books out there are focused on vision, speech synthesis, and projects that don't quite relate to the audio in/out use-case here.  For a beginner (or maybe just me,) it makes it hard to know where to dedicate my time.

You're likely busy, and I fully expect the answer to be "no," but I hope it doesn't hurt to ask anyways: if you do have some time available, I'd be happy to donate or pay for your time if you're able to share some tips, or hop into a quick session to share some basics and methods.

**Comment by sdatkinson** [comment]
> I got it running using the tensorflow migration tool and by importing tf-slim for layers, and the results are so much better than the other models I've tried so far. Of course, let me know if I should share the changes that got things working, if you're at all interested.

That's great! Sure, feel free to PR and I may have a look today before the work week kicks in :)

> I'll try and pick through and figure out why your method seems to hone in on a reasonable result soooo much faster than PedalnetRT here on github for example (using pytorch_lightning.) I know this is just about the least technical description I could come up with, but running your model for about 10k minibatches finishes in just a couple of minutes. If I run the PedalNetRt model for 90k Epochs, it runs for about 10 hours, and the results are about on par with your model here, but in some ways even less impressive (missing/rounded transients, etc...)

Just checked that out...I haven't really been paying attention to developments in this space since I stopped working on this but I figured back then that it should basically get figured out in the next few years.  I'm vaguely aware of the WaveNet paper that it looks like PedalNet is based on...actually, looking closer, I think it looks kind of similar to the architecture I came up with. Not sure if I ever put them out there, but I remember they _did_ do quite a bit better than what I've got here (error down by ~3x IIRC)...but if it's not in the repo here I'm not sure where they went.

It's worth noting that "minibatch" here probably =/= epoch in PedalNet, so that's probably not apples-to-apples...but yeah if the results are good, then that's what ultimately matters. Also FWIW the architectures I used here are probably a bit off from being a reasonable "real-time" solution (should prune etc) but hopefully aren't far off.

> Any tips or reading material you suggest would be appreciated; It seems most of the machine learning books out there are focused on vision, speech synthesis, and projects that don't quite relate to the audio in/out use-case here. For a beginner (or maybe just me,) it makes it hard to know where to dedicate my time.

Right. The biggest challenge is resolution: sound is O(10k) samples per second; ImageNet is O(100) pixels per edge, and NLP tasks have a characteristic "length scale" of a handful of tokens (sentence-level)  and SoTA is still quite small relative to sound.  This also seems to make RNNs tricky. I tried a few but didn't get good results though I think these ultimately have the best prospects for real-time. Something strictly autoregressive like this, even with convolutional layers instead of fully-connected, just _feels_ really clunky...but it's a start.

> You're likely busy, and I fully expect the answer to be "no," but I hope it doesn't hurt to ask anyways: if you do have some time available, I'd be happy to donate or pay for your time if you're able to share some tips, or hop into a quick session to share some basics and methods.

Right, this is strictly "for fun" :) Best bet is to open a PR if you've got something to add or if you've got something specific you're wondering then feel free to open an issue.

**Comment by sdatkinson** [comment]
BTW you've successfully convinced me to port the code to PyTorch, so I'll have that option here soon (no clue how its speed compares to the old TF1 code though.  Still looks like ~minutes for 10k iters though :) )

**Comment by ThreepE0** [comment]
That’s great thanks again! I’ll definitely keep an eye out for a new repo
from you, excited to see it! I’ll submit a PR later today for what I got
working too.

**Comment by sdatkinson** [comment]
[PyTorch branch](https://github.com/sdatkinson/neural-amp-modeler/tree/pytorch)

Still all sorts of crud in there but at least you don't need a shovel to unearth the dependencies!

**Comment by ThreepE0** [comment]
I am baffled by the speed at which you turned that around 😆 taking a look
in an hour or so thank you!

Aspiring to have as solid a grasp on this stuff as you very apparently do

**Comment by sdatkinson** [comment]
Coming back to this: I ended up going w/ PyTorch / Lightning :)
