### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/neural-amp-modeler#100]
I am training on Windows using Anaconda and the colab file (I think). I followed Tudor's youtube video.

I have 2 questions:

1: How do I stop training a model but still have it export? Currently I only know of hitting CTRL C which cancels everything, closes Python and doesn't export a model.
2: How can I continue training an exported model to try for a lower ESR?

**Comment by sdatkinson** [comment]
1. The "Ctrl+C" trick is a PyTorch Lightning trick and seems to be a little futzy for me as well recently. If we want this to be more solidly-supported, then I might take it into my own hands. (If so, it'd be good to have an Issue with that as the name so I don't lose it).
2. This is supported in the CLI-style training where the data, model, and learning configurations are specified with JSONs.. You can either:
  a. Initialize the weights from a checkpoint and start a new training run by putting in the following in `model.json`: as another line alongside `"net"`, `"optimizer"`, and `"lr_scheduler"` you can put `"checkpoint_path": "path/to/your/checkpoint.ckpt"`
  b. Continue the same training run from a checkpoint (note: this will remember what epoch it was on, so it will stop immediately if it ran to completion and you didn't bump up the epoch count!): in the `learning.json`: inside `"trainer_fit_kwargs": {}` , add `"ckpt_path": "path/to/your/checkpoint.ckpt"` (note that it's `ckpt` instead of `checkpoint`. This is Lightning's thing, so don't ask me why they're different! 😉)

**Comment by jaredbehrens** [comment]
Thanks. I have saved #2 in a text file to try later and I will start a new issue for #1
