### ISSUE TITLE
[FEATURE] Have a turn-key training demo

### ISSUE THREAD

**Issue by cdicle** [sdatkinson/neural-amp-modeler#126]
I would appreciate it if you could provide a turn-key demo that showcases the training. This will help any prospective contributor, like myself, to have a quick idea about the repo.

**Comment by sdatkinson** [comment]
Does [Easy mode](https://colab.research.google.com/github/sdatkinson/neural-amp-modeler/blob/main/bin/train/easy_colab.ipynb) fit this ask?

If not, it'd help to hear what other things you'd like to see to help you out

**Comment by cdicle** [comment]
Almost, yes. But something I can run locally. The desired workflow experience is below (following your README)

1. Clone the repo
2. Create the nam environment
3. Download input.wav and demo_output.wav to a designated folder, e.g. data/demo . Note that providing both input and output samples is important for smooth developer experience. 
4. Run demo_train.py (training runs on CPU because we want to ensure it works from the start. We can set the max epochs to a low number just to show the process flowing)

Having those, I can immediately jump into demo_train.py, place debug points in the code, and start analyzing the variables, dependencies ...etc. in no time. I can start implementing my changes and test the pipeline without having to figure out quirks of reamping my guitar or finding a sample output.wav from the facebook group ...etc.

I hope this makes sense

**Comment by cdicle** [comment]
@sdatkinson see this [PR](https://github.com/sdatkinson/neural-amp-modeler/pull/138) as a candidate solution

**Comment by sdatkinson** [comment]
Gotcha.

Like I said in the PR, I suspect that the direction under [Train models (Python script)](https://github.com/sdatkinson/neural-amp-modeler#train-models-python-script) then might be a better starting place to get there?

The feedback about providing some ready-to-go audio files sounds good to me--and perhaps the most substantial change to get this there. I could link up a pair from my Google Drive in the README so that they should drop right in?

**Comment by sdatkinson** [comment]
Here's some ingredients:
* Input audio file: [v1_1_1.wav](https://drive.google.com/file/d/1v2xFXeQ9W2Ks05XrqsMCs2viQcKPAwBk/view?usp=share_link)
* Output audio file: [overdrive.wav](https://drive.google.com/file/d/14w2utgL16NozmESzAJO_I0_VCt-5Wgpv/view?usp=share_link)

These can be dropped into [single_pair.json](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/data/single_pair.json) with no other changes (user would do this according to how they wanted to organize their audio files).

But you could PR in the following changes to the model & learning JSONs:

On the model side, tweak [wavenet.json](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/models/wavenet.json) to the "feather" architecture by:
* Halve the 16's and 8's used in `channels`, `head_size`, and `input_size` to 8 & 4

Then for the learning config, drop [`"max_epochs"` from 100](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/learning/default.json#L12) to 10.

In fact, instead of modifying the existing JSONs (which mirror the configuration used as default in `easy_colab.ipynb` and the GUI trainer), you could PR in copies of the model & learning jsons as e.g. `demo.json` under their respective directories and modify the parameters as above for explicit use as a lightweight demo.

**Comment by cdicle** [comment]
@sdatkinson noted. I will update my PR and resubmit accordingly.

**Comment by cdicle** [comment]
@sdatkinson please see this new [PR](https://github.com/sdatkinson/neural-amp-modeler/pull/150) which implements the changes that you mention.
