### ISSUE TITLE
[FEATURE] Performance vs quality tradeoffs

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#142]
I'm opening this to have a place to discuss performance vs quality tradeoffs in the model architectures - specifically with regard to how expensive they are to play back.

While I think there may still be some performance gains to be had by optimizing the playback code, I think the core determining factor is now how "heavy" the model is.

NAM "standard" models currently runs acceptably well on modern PC hardware, but this starts to break down if multiple instances are used. They are also too heavy to run on less powerful processors (a Raspberry Pi 4, for example, can just barely run a "feather" model).

Are there other architectural changes we can investigate to potentially improve performance?

**Comment by sdatkinson** [comment]
Definitely.

There's more tweaking that could be done in the WaveNet to lighten it further (move layers from the 8-channel stack to 4, even fewer channels). It's hard to explain exactly which parameter settings are valid and which aren't, but having a look through the [WaveNet paper](https://arxiv.org/abs/1609.03499) is probably worth it if you want to be diving deep on this (there are slight differences between the model in the paper and in NAM, but they're mostly inconsequential).

In addition to the WaveNet, thee are other architectures altogether in there--check out [`Model.parse_config`](https://github.com/sdatkinson/neural-amp-modeler/blob/75a1b3442d1b0bab2e74f88ee8fe6451866a93c7/nam/models/base.py#L128). I don't _think_ the ConvNet is worth paying attention to, but the LSTM would be a pretty common choice that others have used. It's just a lot more finicky to train, and usually ends up noticeably less accurate..

**Comment by mikeoliphant** [comment]
I agree that LSTM is worth keeping an eye on. It is definitely less heavy to play back.

Subjectively, though, the LSTM models I've used so far have definitely not sounded as good as even the "feather" version of WaveNet models.

I think it would be great to have LSTM in the "easy colab" architecture mix along with the set of WaveNet presets to test them head to head for quality vs performance. Unless I'm misunderstanding something, the current plugin should be able to play them.

**Comment by sdatkinson** [comment]
You're right--all of the other models are fully-supported by the plugin :)

It's just that the LSTMs are a pain to train--I can already imagine the posts saying "Stay away", "Worthless", etc...but I'd like to keep it in here and working via the less "easy" scripts so that folks that want to go deep have it available.

**Comment by mikeoliphant** [comment]
Agreed that it makes sense to try to avoid sending casual users off into the weeds.

That said, it would be really nice to have the convenience of the easy colab setup with more architecture options available.

**Comment by mikeoliphant** [comment]
@sdatkinson Can you give me some insight into the lighter WaveNet models?

For example, the "feather" config:

https://github.com/sdatkinson/neural-amp-modeler/blob/75a1b3442d1b0bab2e74f88ee8fe6451866a93c7/nam/train/core.py#L223-L247

The "channels" and "head_size" in the first layer config correspond to "input_size" and "channels" of the second layer?

It looks like dilations 128-512 from the first layer have been moved to the beginning of the dilations for the second layer? What does that do? I tried running a model where both layers had dilations of "[1, 2, 4, 8, 16, 32, 64]". It worked, but was significantly less accurate.

Any tips you can provide on what values might make sense to tweak to try to get lighter-weight models would be greatly appreciated.

**Comment by mikeoliphant** [comment]
I'm happy to report that with a combination of NAM tweaks (fast tan), and OS tweaks (64bit instead of 32bit was key), I now have full "standard" NAM models running great on Raspberry Pi 4.

**Comment by 2-dor** [comment]
> I'm happy to report that with a combination of NAM tweaks (fast tan), and OS tweaks (64bit instead of 32bit was key), I now have full "standard" NAM models running great on Raspberry Pi 4.

Wow !!

**Comment by 38github** [comment]
> I'm happy to report that with a combination of NAM tweaks (fast tan), and OS tweaks (64bit instead of 32bit was key), I now have full "standard" NAM models running great on Raspberry Pi 4.

Can this be why the compile yesterday of your LV2 version suddenly only used 1% (average, 6c/12t) using my Ryzen 5600G? I was really surprised.

**Comment by mikeoliphant** [comment]
Partly. The LV2 version uses fast tanh (https://github.com/sdatkinson/NeuralAmpModelerCore/issues/30) , which is a big win.

On Rasbperry Pi, another key step was moving to a 64bit version of the OS.

**Comment by sdatkinson** [comment]
> The "channels" and "head_size" in the first layer config correspond to "input_size" and "channels" of the second layer?

That's right. There's a convolution that starts off each block of layers to get the number of channels from the input to the "main" number of channels that the individual WaveNet layers (with skip connections) use. So the input to the second block of layers is the output of the first; they need to match up.

> I tried running a model where both layers had dilations of "[1, 2, 4, 8, 16, 32, 64]".  It worked, but was significantly less accurate.

This affects the _receptive field_--how far into the past the model can "see" when making a prediction.  Have a look at Sec 2.1 of the [WaveNet paper](https://arxiv.org/abs/1609.03499) for an explanation with figures. So two blocks of 1,2,4,8,16,32,64 (and a kernel size of 3!--note that the paper shows figure with kernel of size 2) should have a receptive field of about (mental math...) 512 samples? Or about 10 ms at 48k.

**Comment by mikeoliphant** [comment]
Thanks - that makes sense to me. What I'm not understanding is the dilations in the second layer of the current "feather" config:

[128, 256, 512, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

Why the "128, 256, 512" at the start?

**Comment by sdatkinson** [comment]
> Why the "128, 256, 512" at the start?

Just pulled them down to the second (lighter) block from the first.

Technically a "real" WaveNet is just one of these blocks, so it'd be like `[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512]` all in one.

There's some flexibility to this, but the biggest rules are:
1. Don't leave any gaps. E.g. `[1,3]` with a kernel size of 2 would miss every third sample when making predictions (which should be bad since you're missing inputs.)
2. Make sure the receptive field is big enough to be able to see all of the relevant inputs.

Parenthetically, the "2x512" architecture above, which is 20 layers deep, has the same receptive field as a "1x1024" (instead of going back down to 1 and counting up again, put on one more layer with a dilation of 1024), which only has 11 layers (and is therefore about twice as light to run), but has the same receptive field...it's just that the other pattern results in more "space" inside the model to compute (and the "standard" model, which uses a kernel size of 3, also "overlaps" some of its samples, which further improves the "density" of computations in the net...seems to be a good thing.

**Comment by mikeoliphant** [comment]
Thanks - I'm not sure I'm quite there in terms of understanding everything, but that info definitely helps a lot.

**Comment by sdatkinson** [comment]
Closing this; feel free to re-open if you have any other questions :)

**Comment by jdolarte** [comment]
Hello, I'd like to request reopening this issue as I'm interested in WaveNet model pruning.

Regarding the default activation function used in WaveNet, I noticed that it's tanh (or recently Fast Tanh), which is computationally more expensive than ReLU and less quantization-friendly. I was wondering if the choice of tanh was made because of its benefits in the training process, or if you noticed any audio quality improvement compared to ReLU?

Thank you for your attention!

**Comment by mikeoliphant** [comment]
ReLU only has positive values, which makes it not a good alternative to Tanh for training.

On the playback side, we use a fast tanh approximation, which does a pretty good job.

I've also experimented with Hardtanh, which seems like it might work well.

See here:

https://github.com/sdatkinson/neural-amp-modeler/issues/197

Hardtanh is supported by the playback code, so you can experiment with it if you use a modified WaveNet model for training (PR https://github.com/sdatkinson/neural-amp-modeler/pull/238 would make this easier to do).

**Comment by jdolarte** [comment]
I think ReLU activations shouldn’t be avoided just because the input can have negative values, neutral networks' weights and biases are not restricted to being positive or negative. The features are multiplied with weights that can be negative as well, thus making the actual inputs to the neuron positive. In the final layer a different activation function that allows negative values could be used, but as I understand, the model has a convolutional layer at the output (a linear operator) so negative weights will result in a negative output.

I was primarily concerned about the audio quality of models trained using ReLUs, as I read an article suggesting that ReLUs may not be the most effective option for achieving optimal audio performance.

**Comment by 38github** [comment]
I have now tried using ReLU activation and it works great when increasing the kernels to 5 and higher. I also lowered dilations and head and I now get really good models with CPU just below the Standard settings with Tanh.

```
       "condition_size": 1,
                    "input_size": 1,
                    "channels": 7,
                    "head_size": 5,
                    "kernel_size": 7,
                    "dilations": [1,2,4,8,16,32,64,128,256,512],
                    "activation": "ReLU",
                    "gated": False,
                    "head_bias": False
                },
                {
                    "condition_size": 1,
                    "input_size": 7,
                    "channels": 5,
                    "head_size": 1,
                    "kernel_size": 7,
                    "dilations": [1,2,4,8,16,32,64,128,256,512],
                    "activation": "ReLU",
                    "gated": False,
                    "head_bias": True
```
