### ISSUE TITLE
[FEATURE] Allow for training on a multiple GPU system using DDP

### ISSUE THREAD

**Issue by rossbalch** [sdatkinson/neural-amp-modeler#146]
Currently it is not possible to train models on a multiple GPU system where learning rate could be handled very quickly.

**Comment by sdatkinson** [comment]
Lightning supports DDP; should be possible to flip it on.

Personally, I'm skeptical that it will improve performance--these are tiny models, and operation out of the GPU-saturated regime seems to give the best results in terms of wall time.

If you find otherwise, I'd be interested if you shared your findings. But, without that, my suspicion is that this isn't a good idea for this particular use case, so I'm going to close this for now.
