### ISSUE TITLE
[FEATURE] Implement auto output audio alignment and clipping

### ISSUE THREAD

**Issue by cdicle** [sdatkinson/neural-amp-modeler#151]
We would like to make modeling workflow as seamless and automated as possible. Currently users need to align and clip their output audios manually using their DAWs. Even though this step does not create a big context switch, it is an error-prone manual step in the workflow. Automating that step will improve both smooth workflow and quality control. 

The functionality is relatively easy to implement either as a step in the data pipeline, or as a script or both.

**Comment by sdatkinson** [comment]
At face value, I agree.--in `bin/train/main.py`, it'd be great if `"delay": null` in the data JSON called [the existing alignment code](https://github.com/sdatkinson/neural-amp-modeler/blob/75a1b3442d1b0bab2e74f88ee8fe6451866a93c7/nam/train/core.py#L144).

The main issue I see is: How do you know that the data configuration matches to a data set where the alignment _can_ be done? v1_1_1.wav is special because it has the spikes at the beginning, but the general data configuration JSON makes very minimal assumptions about the content of the audio being used.

I can think of a few options. Off the top of my head:
* Special "versioned" data set where the input is assumed to match something specific
* Additional fields like `"align_start"` and `"align_stop"` to indicate that the content in that interval should be "something from which an alignment can be estimated." (e.g. minimally, that the input is silent followed by something non-silent...but perhaps it should also be required to be silent for some minimum amount of time so that nothing happened "just out of view" before the slice.)

**Comment by cdicle** [comment]
Good points. Here are some answers
 * In a modeling task there is practically no problem assuming full knowledge and control of the input signal. Hence, one can design the input whichever way fits the task.
 * Even if we relax the input structure assumption, I expect the input and output to be strongly correlated. I can think of exotic rigs that can break this assumption like with heavy reverbs, wah, fuzz ...etc. but we can treat those as special cases. We can test this idea by taking adequately long portion of the input signal and attempt an alignment.  
 * Not ideal, but we do not have to pick one or the other. We can make this an option and let the user choose, or we can autodetect the input like you do currently and attempt auto-align if the input is a known version to us. 

All in all, I believe there are ways to better streamline the capture process. This is not a critical feature currently. I see auto-alignment particularly being useful when we want to model the gain, presence like knobs. We will potentially ask user to capture at the order of a dozen outputs. These automating tools will establish a standard to the process. Sidenote - I have the prospective architecture ready for a POC training. 

Let me know what you think.

**Comment by cdicle** [comment]
@sdatkinson I would appreciate if you progress the conversation and decide whether to integrate this feature or not. I have an open [PR](https://github.com/sdatkinson/neural-amp-modeler/pull/157) from two weeks ago which may benefit your review. 

Based on our decision, I can consider taking up on improving CPU usage.

**Comment by sdatkinson** [comment]
> * In a modeling task there is practically no problem assuming full knowledge and control of the input signal. Hence, one can design the input whichever way fits the task.

That's true, but _requiring_ "odd" knowledge is a recipe for user error or will require a lot of data validation & writing error messages.

> * Even if we relax the input structure assumption, I expect the input and output to be strongly correlated. I can think of exotic rigs that can break this assumption like with heavy reverbs, wah, fuzz ...etc. but we can treat those as special cases. We can test this idea by taking adequately long portion of the input signal and attempt an alignment.

This seems to be what the PR attempts. The problem with vanilla correlation is that it's not causal--getting it wrong by a sample and predicting a lagged output is no problem; getting it wrong in the other direction means you need to predict the future, which immediately tanks the accuracy. So I'm skeptical that this will work, but could be convinced if you showed that it worked as well as / better than the trigger-based code that's currently used.

> * Not ideal, but we do not have to pick one or the other. We can make this an option and let the user choose

I'm somewhat against this on principle: Instead of widening the surface area of the core library, I'd rather have folks build their own code to solve this problem their own way if this didn't suit them, then write the answer into the JSON that they provide as input. It's already a bit beyond my liking for this package to have _any_ alignment code, except for that the "batteries included" training options (Colab, GUI) are also part of this repo. It may be wiser to trim down this repo to something more minimal, so that different training scripts could be written using it with whatever flexibility the downstream case has in mind...but I don't think that's an urgent need.

---

To wrap this all up and propose a way forward, if we wanted to give `bin/train/main.py` the same capabilities as the others (usable under the same conditions i.e. recognized data) as I said in my initial comment, then that might be a good way to get everything on the same footing and have any subsequent movement lift all the options together. But I would like to keep `bin/train/main.py` as the most "customizable" pre-made training solution, generally.

**Comment by cdicle** [comment]
Fair points. I will request raw output recordings from the community and evaluate the result on them. 

One quick response though. Your current solution heavily relies on assumptions above, i.e. "odd" knowledge of the input, semi-auto alignment, danger of non-causal treatment. Our confidence comes from seeing it working so far, i.e. statistical. We can apply the same criteria to the proposed solution. 

I will keep you posted.

**Comment by KaisKermani** [comment]
I believe this is related to this feature here:

I have a capture file that the NAM easy_colab training notebook is refusing, with the error `Output clipped.Source is output.wav`
I made sure that there's no clipping in the output.wav file, so I believe there must be some issue in the checks?

Here are the capture files in case you want to investigate as well:
https://drive.google.com/drive/folders/1ITdra_GJ5zheMq60Xrib_Pl_wEbcpMiq?usp=sharing

**Comment by sdatkinson** [comment]
Coming back to this. I'm happy with the method that's used to align standardized data in the simplified trainers (GUI, Colab), and I'm not keen to make a change to the CLI trainer to auto-align. I'm more convinced now that it just isn't the right way to go for a general-purpose trainer like the CLI is meant to be.

---

@KaisKermani , there is indeed an issue with your output: it hits 1.0, which means it might have clipped:
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/2fbc5062-5782-4418-8be5-f56e551f33ef)

There's no way to hold a larger value than this (hence "clipping") so this is as strong an evidence that one can get. I'm guessing that you peak-normalized your output file to full scale? That's generally not something I'd recommend doing--the inability to tell whether you clipped during recording is one reason why.
