### ISSUE TITLE
[FEATURE] Group of models for one amp with different settings

### ISSUE THREAD

**Issue by gtirard** [sdatkinson/neural-amp-modeler#188]
When the user captures the same amp with different settings, it's always difficult to read the files names to understand the corresponding settings.

It would be nice to be able to load a group of models with virtual controls corresponding to the amp's setting. Instead of loading each model one by one, trying to guess the original amp's setting by reading the name of each model, the end user would select options in the UI, and it would load the corresponding model.

Suppose we have these models for the Roland Jazz Chorus:

![image](https://user-images.githubusercontent.com/668338/232003519-dabfade5-2ea9-427f-9225-9b13e9bd453d.png)

We would create a JSON conf file, to link these models together, and be able to show them a different setting of one amp, like this:

![image](https://user-images.githubusercontent.com/668338/232003817-6a151aae-2fdc-4562-9579-2476d7268452.png)

In that example, if the user selects "Channel 2" and "high", it would load the model "Tim R JC 120 CH 2 Hi.nam"
Other UI elements could include ratary knobs for different gain values, etc.

**Comment by deduble** [comment]
I think a better approach would be to add the amp settings together with audio as input so that we get a smooth representative output.

**Comment by kar-pos** [comment]
I think this feature should be high-priority. It is absolutely "must have" because in current form, some amp models are in the form of package not 4 but over a dozen of files with unclear description. I think this lack of clarity is one of the biggest downsides of this great tool.

**Comment by Chrisedmo** [comment]
Love this idea! I wonder If it's something in the meta data for captures that a capture can be part of a group...? And then initiates a drop down?

**Comment by EgonTwo** [comment]
I think file management should be top priority. As great at this plugin sounds (and it has become my go-to for guitar amps now) managing the files has become too cumbersome.

I wonder if a "set" of files ie: different settings of one amp could be kept inside a zip file, and read from the plugin as a single instance of that amp. 

At the very least, it would be more convenient if it were possible to store the *.nam files in different folders, ie: Fender, Mesa, Marshall, etc. which could be accessed from within NAM. I tried using separate folders, but NAM only reads from the root.

**Comment by sdatkinson** [comment]
Thanks all for your patience with the delayed response on this.

Punchline first: This isn't something that I'm going to make changes to the (now*) existing code to change how it's supported currently.

Read on please for an explanation of what I'm going for instead & why. The TLDR is that the libraries and components I've open-sourced are designed to allow others to build all sorts of options like these already, as well as solutions that are even better than the ideas in this thread 🙂

@gtirard 

> It would be nice to be able to load a group of models with virtual controls corresponding to the amp's setting.

This is about the plugin's UI, not the training process, so it's out of scope for this repo ([neural-amp-modeler](https://github.com/sdatkinson/neural-amp-modeler)). You want [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin), which contains the code to make a plugin that runs the models created by this repo using the core DSP code contained in [NeuralAmpModelerCore](https://github.com/sdatkinson/NeuralAmpModelerCore).

> Instead of loading each model one by one, trying to guess the original amp's setting by reading the name of each model, the end user would select options in the UI, and it would load the corresponding model

As of plugin version [0.7.4](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.7.4), users can now page through models that are in a folder with some arrows on the GUI. If the alphabetical ordering of the model names is what you want, then you can scroll through using the arrows now. (I see you suggested this before that release was published, so perhaps this works for what you had in mind?)

So **punchline 1: I believe that the "arrows" in the plugin give you the ability to do what this Issue originally asked for.**

> In that example, if the user selects "Channel 2" and "high", it would load the model "Tim R JC 120 CH 2 Hi.nam"
Other UI elements could include ratary knobs for different gain values, etc.

The problem with this UI is that the various knows & switches for models are really varied--it'd be difficult to make a single UI that can handle all of the cases out there, especially as a "loader". This is why parametric models released by companies generally have customized UIs for each amp...but you can certainly build things like those using the pieces that I've open-sourced 🙂

The practical challenge is that I can either choose to follow one specific specialization, or I can keep this repo as "unopinionated" as possible so that it can be built _on_ in those ways. I've thought about this a lot and am opting for the latter: given the amount of use cases that the libraries I maintain have to be able to support, I'm not going to be moving these repos in a way that "plays favorites" toward one solution or another--but that'd be something that someone else is welcome to build on top of this according to how they want to customize it.

@deduble 

> I think a better approach would be to add the amp settings together with audio as input so that we get a smooth representative output.

Good news: making parametric models via concatenating controls with the signal is already supported by this library--see [`nam/models/parametric/catnets.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/06547c8579cbec9f0eb4f8ca732083e91b672e4e/nam/models/parametric/catnets.py) 🙂 In short, this is the reason that I don't want to get too deep into approaches that cobble snapshot models together--this is (in my opinion) so much nicer.

So **punchline 2: parametric models are already in the code, and they're a great (albeit somewhat difficult to make) solution.** Due to the difficulties of making them and coding the plugin for them, I don't have the bandwidth to support "user-level" interest. I'll be focusing on interest from builders so that I can enable them to build their stuff on what I've put out.

@Chrisedmo 

> Love this idea! I wonder If it's something in the meta data for captures that a capture can be part of a group...? And then initiates a drop down?

This can be done (by the plugin at [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin) by putting models together in a folder 👍🏻 

@EgonTwo 

> At the very least, it would be more convenient if it were possible to store the *.nam files in different folders, ie: Fender, Mesa, Marshall, etc. which could be accessed from within NAM. I tried using separate folders, but NAM only reads from the root.

We played around with a version of the plugin where the files in the dropdown were populated recursively. We chose not to do it because we had instances where the dropdown would surprisingly "blow up" if you picked a folder that happened to have thousands of models under it 😅 We (myself and some testers) thought it was unintuitive to have models that weren't visible when you were in the file browser show up--and doubly so when everything got alphabetically-organized, jumbling the contents of the folders...hence the solution to read only what's directly contained in the selected folder.

_*I realize this Issue was first requested in April and that things have changed since then. Again, thanks for your patience with this._
