### ISSUE TITLE
[FEATURE] Possibility for profiling specific segments of the amp and loading multiple profiles in parallel? 

### ISSUE THREAD

**Issue by jimc4893** [sdatkinson/neural-amp-modeler#192]
To capture every EQ setting for realistic EQ knobs in the plugin, it would take tens of thousands of captures. Would a good workaround be to profile every setting for each knob and then use a few different user selectable filters to create a multiband profile that would allow for realistic knob movements? 

I know that the knobs are going to affect other bands, but if the eq curves between bands overlapped, there may be enough overlap of frequencies to make it sound more realistic.

**Comment by sdatkinson** [comment]
What you want is ["parametric modeling"](https://www.youtube.com/watch?v=WYVzdTE3Tsg)--see `nam/models/parametric`.

Unfortunately it is a bit nontrivial to collect the appropriate data to use it, so in order to simplify this package for the majority of folks who are only interested in the "snapshot" modeling, I'm going to be deprecating it from this open-source package in the next breaking release--see #334--but I will leave the door open in this package for folks interested in it to keep the model classes and data sets themselves and register them in the `nam` package, allowing them to continue to use the rest of what this package offers.
