### ISSUE TITLE
[FEATURE] Add skip connection option for LSTM

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#249]
It would be nice to allow an optional input->output skip connection for LSTM networks.

From looking at the code, "_SkippyLSTM" seems to be for that? But it looks out of date.

Having it be an option on the main LSTM model implementation could work?

**Comment by sdatkinson** [comment]
Good eye :)

Currently, I'm not working on `SkippyLSTM` because it's not efficient to run with vanilla PyTorch (it needs to be compiled to run or else it's crazy-slow in Python).

Also, I'm not sure if it's even worth the trouble (i.e. does it even perform better? complex ideas have a way of disappointing in ML! 😉)

So it's not a priority atm, and the skips are a bit nontrivial (not just the usual skip connection you see in the literature).

**Comment by mikeoliphant** [comment]
The way I've seen it implemented is that the input is simply added to the output during feedfoward - so the network is essentially learning the difference between input and output.

Here's an example implementation:

https://github.com/Alec-Wright/CoreAudioML/blob/f3a07c415ba134efca2a6968c15b56cc6e33a18a/networks.py#L16

Whether it helps, I don't know.

**Comment by sdatkinson** [comment]
Ah, yeah.

Basically, I recall trying that after seeing others do it, though it doesn't seem like a reasonable thing to do in this case here in my judgment (and IIRC it didn't seem to help).

But if that doesn't satisfy you, could mod the LSTM architecture to do this (if it's not already still in there...haven't checked recently), run some experiments, and I'd love to know if I'm wrong 🙂

**Comment by mikeoliphant** [comment]
I haven't tried skip connections specifically with NAM, but I did do some experimentation a while back with CoreAudioML and it didn't seem to be clearly useful. I'll close this, as it doesn't seem like a good use of time to add it to NAM.
