### ISSUE TITLE
[BUG] Delay safety factor results in 4 sample delay for perfectly aligned captures

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#269]
If you have a capture that is perfectly aligned with the training .wav, NAM will correctly detect a 0 sample offset but then adds a 4-sample safety factor.

This was clearly done intentionally, but it will result in a model with a 4-sample delay.

Interestingly, my testing shows that the delay might actually help training (maybe because it allows the model to see a few samples "into the future").

The delay should probably either be eliminated, or (if it serves a useful purpose) reported by the model to the plugin so that it can be compensated for.

**Comment by sdatkinson** [comment]
The purpose of the delay is that it can be a little tricky to tell exactly what the delay is when the reamp is a little noisy. Even if the amp is "reacting", it can be a few samples before the response gets over the noise floor. So the "4 samples" is a bit of a kludge to just make sure that it's not being asked to "predict the future".

I've sort of kept an eye on it, but I'm not 100% confident it's exactly the right value or might be better-tuned. But a little bit of delay is much better than being even a single sample on the wrong side (the error skyrockets).

But if you've got the bandwidth and interest to dig deeper into it and think you can tune it to work better, I'm happy to hear what you find 🙂

**Comment by sdatkinson** [comment]
Forgot to mention: the colab/GUI trainers provide the ability to explicitly provide the delay if you know it exactly (as you mentioned you "know" that your files are perfectly aligned--so you could provide a delay of zero in that case). (See: https://github.com/sdatkinson/neural-amp-modeler/blob/3cf65f56ddd1762e026d53e0adc54753ddc4dae0/nam/train/colab.py#L72, default is `None` which tells it to try and figure it out for itself.)

The subtlety is that it's 4 samples ahead of where the signal crossed the threshold, but the amp could have (and probably is) reacting before that point. The "4 samples" is a crude guess, but the fundamental thing is that there's uncertainty because the data are noisy. So I'm not sure it'd be correct for it to report to the plugin that it's 4 samples behind--it's probably less than that by a little bit, give or take.
