### ISSUE TITLE
[FEATURE] Train direct and mic'd tones in the same pass

### ISSUE THREAD

**Issue by MirrorProfiles** [sdatkinson/neural-amp-modeler#276]
**Is your feature request related to a problem? Please describe.**
Currently it requires several passes of uploading files and inputting data for related captures. With mic'd models now better supported, it would be great to upload an amp DI and mic'd tone as well as the training file.

**Describe the solution you'd like**
It would be great to upload the training file, a direct "amp DI" file, and a mic'd file, and  for the training to process each (as well as apply appropriate metadata). In the future there could be the ability for the plugin to switch between direct and mic'd without needing to load 2 different files. It could also be possible to automatically create an IR from the included files.

**Describe alternatives you've considered**
Doing them seperately is fine, but it gives more chance for inconsistencies in naming or organising things incorrectly. 

**Additional context**

**Comment by sdatkinson** [comment]
Hmm. Tricky.

Best I might suggest is that, if you're trying to go through a bunch of models, you might do all of the cabless runs together*, then do the switch once and run the cab'd runs together. This would reduce the amount of changes to just one (assuming that the batch of runs otherwise have the same metadata. If they don't, then I feel like this wouldn't do _enough_ to relieve the pain to be worth the trouble; and if it's only 2 models total, then I don't think the pain point is too high.)

The challenge with coding something up is it seems like it'd be sort of difficult to indicate which files are which, and what exactly the relationship between the two is in the metadata. Given the complexity versus how often I'm guessing this might be used, I think I'm going to close this as a "won't do" for the forseeable future.

*To queue up a batch of runs with the GUI trainer, ctrl+click the output WAVs together during the "Output Audio" selection step.
