### ISSUE TITLE
[FEATURE] Add option "Shutdown pc after batch training"

### ISSUE THREAD

**Issue by Jesco-White** [sdatkinson/neural-amp-modeler#290]
It would be a nice feature in the trainer if there was a checkbox option to shutdown your pc after the (last) model is trained (in a batch).

**Comment by vossenv** [comment]
Wait, you mean you actually turn off your PC sometimes?

**Comment by sdatkinson** [comment]
Hi, @Jesco-White!

If you want to do that, you could use the training script [`bin/train/main.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/main.py) within a shell script that calls a shutdown after finishing.

But in terms of a button e.g. on the GUI trainer, I'm not really keen on expanding the scope of this project to implement it due to the cost of testing it.
