### ISSUE TITLE
[QUERY] Is there optimization margin yet?

### ISSUE THREAD

**Issue by jcorfer** [sdatkinson/neural-amp-modeler#314]
I'm using NAM on Ableton on an empty project with only one track for the VST and I'm getting CPU spikes at 128 samples and 48Khz. My machine has Ryzen 7 4800h, 16Gb, 1Tb SSD, Windows 10 and my audio interface is EVO 16. I think that everything should be work fine, but It doesn't seems.

I would like use the NAM for record and live shows, so I would like to know if NAM is more optimizable or not.

Thank your for your work!

**Comment by sdatkinson** [comment]
Thanks for your question. The answer to it is yes--I'm sure there's plenty that could be done to improve its performance.

However, I don't know how much juice there is left to squeeze.

In the meantime, if you're having trouble running your models, then you might consider re-training them with a lighter architecture. E.g. if you're using the simplified trainers, instead of using "standard", use one of the lighter modes (lite, feather, nano).
