### ISSUE TITLE
[Not a BUG exactly] How to use Tensor Cores while training (RTX 3080)?

### ISSUE THREAD

**Issue by StanislawKarnacky** [sdatkinson/neural-amp-modeler#316]
Got this message while training: You are using a CUDA device ('NVIDIA GeForce RTX 3080 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision"
Is there any chance of passing the argument as suggested above to accelerate training?

**Comment by sdatkinson** [comment]
Yep, potentially.

Questions for me are:
1. Does it actually help?
2. [How] do the predictions change when run "normally" on the CPU the way it'll run in the plugin?

To try this out, just put the line you copied into the script at the top.

Interested to hear what you find.

**Comment by sdatkinson** [comment]
Checked it out myself. I don't see any meaningful difference in speed on my 3070Ti:

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/85a60960-ae97-47f9-b4c3-a5cdb71b5f8b)
_Gray is using Tensor Cores; Orange is without._

This isn't surprising to me--NAM's models are tiny in terms of deep learning while nVIDIA's hardware is going the way of supporting heavy computation.

Closing since I won't be addign it to my repo based on this. If you want to use it, as the instructions say you just have to add 
```python
torch.set_float32_matmul_precision("medium")
```
to the top of the CLI trainer's script.
