### ISSUE TITLE
[FEATURE] GUI / (easy) Colab letting us use custom input file

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#325]
**Is your feature request related to a problem? Please describe.**
I am not able to train captures created from reference files other than the three official ones. This can make a successful training time consuming and potentially impossible if we no longer have the physical equipment at hand to make new captures.

**Describe the solution you'd like**
In the GUI there could be a check box that says something like custom train/input file that automatically disables checksum and further checks which then hopefully would allow us to train. Then there can be a metadata variable/tag that says the .nam was trained not using official files and this indicate that the ESR value probably would not be the same as if used with official files. By that I mean that, I think, a not the some part of the input will be used to calculate the ESR value.

**Describe alternatives you've considered**
None at this time other than I have to use the old manual Colab that does not support all features and it forces me to create further files for the testing which ends up being four files in total instead of two.

**Additional context**
If so, I will update this...

**Comment by 38github** [comment]
While asking for this, between what samples is the test/validation portion split from the files?

**Comment by mikeoliphant** [comment]
> While asking for this, between what samples is the test/validation portion split from the v2_0_0 and output files?

https://github.com/sdatkinson/neural-amp-modeler/blob/62a8f7e47582cc0137831eaa494d99e1659ae0f7/nam/train/core.py#L183C1-L202C2

**Comment by 38github** [comment]
> > While asking for this, between what samples is the test/validation portion split from the v2_0_0 and output files?
> 
> https://github.com/sdatkinson/neural-amp-modeler/blob/62a8f7e47582cc0137831eaa494d99e1659ae0f7/nam/train/core.py#L183-L202

Thank you! I appearantly missed that while looking through the core.py file. Regards

**Comment by sdatkinson** [comment]
The standardized training files do a few things. I remember train/validation split and calibrating the latency as two, but v2 also has additional repeats of various signals to make sure that the amp being modeled is staying consistent. In fact, I'm going to do a little bit of re-shuffling for the v3 of the training file to try and get rid of the false alarms on the signal checking.

It's pretty difficult to guess all of those details from a random training file, and not something I'm going to take on maintaining into the future. If you want to keep using that Colab, you're more than welcome to go back to it, grab it, and save it somewhere for yourself. But the fact it doesn't "support all features" is exactly why I stopped supporting it--because it takes time for me to keep it working along with the other three! 🥴

If you want to customize training, there's still a way to do that that's still supported in this repo. supported option is the CLI trainer whose script is at `bin/train/main.py`. That's the only "advanced mode" training I intend to support. You're of course welcome to modify this repo yourself to make a custom solution that suits your needs.

**Comment by 38github** [comment]
Thank you for the reply.

I was thinking that if a custom input was used then the checks are disabled. It would act like the old colab file but we get the benefits of new features except, of course, checks. Maybe a checkbox next the input box that says _Custom File_ or something.
