### ISSUE TITLE
[FEATURE] FLAC support to decrease file sizes

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#352]
It can save a lot of storage space and Google Colab's upload speed is slow so this would also help there.

**Comment by sdatkinson** [comment]
On one hand, I'm open to loading different audio file formats. At the bottom, the audio loading [comes from `wavio`](https://github.com/sdatkinson/neural-amp-modeler/blob/ae8697914a0ce3f32a4e9e3332d16c12451e5d86/nam/data.py#L82). First step with this would be to suggest to me an alternative for FLAC.

The issue with _Colab_ though (presumably [the simplified trainer](https://github.com/sdatkinson/neural-amp-modeler/blob/e3d1d0b7ba51d08978875641a9dfc2b7ff2c2e66/bin/train/easy_colab.ipynb)) is that I need to be able to tell which of the standardized files are being used so that I can set up training correctly (calibrate latency, do a train/test split that doesn't have data leakage, etc) and I'd need to duplicate the work for these files that aren't actually the exact same, so I'm not really keen on that part--this would be a CLI-only feature (or you'd be responsible for maintaining your own training script--which I'd totally encourage you to look into!)

**Comment by 38github** [comment]
Is it possible to create and check the checksums based on the raw audio itself and not the file? E.g. a FLAC file has in its tags checksum like that.

**Comment by sdatkinson** [comment]
That's how it works currently 👍🏻 

---

Coming back to this, I'm not going to implement it because I don't think that it helps the core aim of this repo, which is to:
1. provide the NAM training code for people to build with, and
2. demonstrate to people how to do (1)

So the way I see it, loading FLAC files is a separate consideration--in fact, getting the audio data in general is separate (it doesn't even need to be from a file--it could be provided directly from a plug-in calling this code).

At any rate, this should be something that someone could either implement in their own project or extend this project either by forking the repo or writing an [extension](https://github.com/sdatkinson/neural-amp-modeler/issues/440).

**Comment by 38github** [comment]
Thank you for the explaination and I can see your point.
