### ISSUE TITLE
[FEATURE] GUI: Add advanced option to do training-time upsampling 

### ISSUE THREAD

**Issue by honkkis** [sdatkinson/neural-amp-modeler#355]
To reduce aliasing it is beneficial to allow training models in 96kHz that also result in models that are run in 96kHz. This is possible and has measurable benefits even with 48 kHz recorded WAVs.

I have implemented this in https://github.com/sdatkinson/neural-amp-modeler/pull/354 . Please let me know whether this can be merged, or whether it needs some changes.

![Screenshot 2024-01-07 at 17 50 05](https://github.com/sdatkinson/neural-amp-modeler/assets/2007263/864da8f8-00ad-4ac2-a433-7d55ef58a6e0)

These spectrograms of sine sweeps through NAM with the same amp model show the reduction in alias when a model is trained and inferenced in 96kHz instead of 48 kHz.

![alias](https://github.com/sdatkinson/neural-amp-modeler/assets/2007263/a052eeed-d101-4b29-8505-f3e07d20c2ca)

**Comment by sdatkinson** [comment]
Hi. thanks for your patience with me getting back to you on this.

Unfortunately, this isn't something that I think I want merged into my repo.

The reason is that, while I do agree with you that it can help in the ways you've shown, the trade-off is, naturally, CPU usage. The other place I've already made a decision wrt this tradeoff is model size and the so-called "standard" architecture.

It's not to say I don't _want_ people making more accurate models--that's why different sample rates are already supported. But, what I choose to expose in the simplified trainers and what defaults I pick has a direct effect on what models people tend to make--and share.

And this directly impacts people's impressions of NAM--the two things people know are (1) "NAM is accurate" and (2) "NAM is CPU-heavy"--both which are a consequence of how I've configured the simplified trainers.

The other reason, which you're seeing with #356, is that this interacts with other parts of the process in subtle ways. By opening up this "axis", there are knock-on effects to how the rest of the code needs to be maintained that aren't worth it from my perspective as a maintainer. Given the options, I would rather be conservative with what I merge into this repo, favoring things with clear value. The sine sweep test doesn't quite hit that mark, but if there were some practical consequence that you discover, I'd love to know and perhaps I would change my mind.

But, as it is, it seems that the "top settings" suggested by the simplified trainers already allow people to get state-of-the-art results that most users are happy with, so I'm not sure more is needed.

Also, along the same theme with #356, that it _could_ help learning longer-term dependencies isn't enough for me to merge it in as one of the pre-configured architectures--I'd like to see that it _does_ help do what it intends to. The options that are already in there are there because they solve pretty important problems like being able to get lighter models (without necessarily totally destroying accuracy) or fixing the latency compensation. Subjectively, I don't think this rises to that level. (But, if you go and show me that this one little trick makes NAM able to model compressors with no other modifications, then that would be something!)

---

I'll emphasize again: you should totally keep using NAM like this if it's what you want to do! But it's not what I want this "base" repo to do.
