### ISSUE TITLE
[FEATURE] Allow custom training test tones as an option on the GUI

### ISSUE THREAD

**Issue by DimGakis** [sdatkinson/neural-amp-modeler#369]
This feature is sure to be embraced by NAM enthusiasts. 

NAM is employed not only for instrument amplifiers but also for profiling studio equipment. In such cases, a more specific test tone would be preferable, such as one designed for vocals only. Using test tones that exclusively contain vocals may yield a more finely tuned profile for vocal applications.

The inclusion of custom test tones with paired output files will encourage experimentation, potentially leading to many interesting results, NAM would be more flexible and open for creative use cases. 

I would appreciate seeing this feature easily selectable on the GUI.

In the event of any synchronization issues with the paired files (using pointers etc.), users can refer to provided instructions for guidance.

I am hopeful to witness the addition of this feature to NAM soon.

**Comment by sdatkinson** [comment]
Hi!

This is already supported--simply remove the training segment of the reamp file and put your own audio in.

For the v3 standardized training files (i.e. just v3_0_0.wav right now), this is [0:17 to 3:00.5](https://github.com/sdatkinson/neural-amp-modeler/blob/7808e90e2a8527adfae42bca4942c3399f2d8f46/nam/train/core.py#L272).

Of course, You'll still be validating on the same audio (I did this on purpose because messing up train/test and doing invalid evaluations is really easy to do if you don't know what you're doing.), but that's probably a pretty minor issue and, as far as I've seen so far, unlikely to matter. If you do want to make up your own validation split, then you definitely want to either be using the CLI trainer at that point (and you should be using the CLI trainer to find out if it's even worth bothering to do that! 😉)

Hope this helps!

**Comment by DimGakis** [comment]
Dear Steven, I appreciate your reply.
 
Unfortunately I can not do that because I already have recorded with my own five minute test-tone some equipment that were rented. I used to be able to train with the same test-tone by modifying a previous version of the trainer with instructions from a YouTube video, unfortunately these instructions don't work in the current version. 
I am clueless what CLI trainer is and  I a noob to programming. 

On the previous NAM trainer the trick was the following:

Inside the "core.py" the line "input_version: Optional[Version] = None,"
Replaced with: "input_version: Optional[Version] = Version(1, 1, 1),"

And I was able to use any test-tone paired with its output file. 

Is there a way to do something similar to this version so I can train with my own test-tone?
If not, can you please tell me how I can find the old version that this trich works?

Kind regards.
