### ISSUE TITLE
[BUG] disagreement metadata is int instead of bool

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#432]
e.g.

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/c9f28035-8e02-4296-9296-8e8ab75ed96e)

Both should be `false`

Issue is in the Pydantic model defining it as `int`.

**Comment by Rodolfo-S** [comment]
Is this as simple as changing the type hinting in `LatencyCalibrationWarnings` class?
https://github.com/sdatkinson/neural-amp-modeler/blob/d55ab734a640ca67c8e28451f6d56a359873e9ef/nam/train/metadata.py#L53

Because the all the places where `disagreement_too_high` is referenced it's treated as a bool. 

https://github.com/sdatkinson/neural-amp-modeler/blob/d55ab734a640ca67c8e28451f6d56a359873e9ef/nam/train/core.py#L398

https://github.com/sdatkinson/neural-amp-modeler/blob/d55ab734a640ca67c8e28451f6d56a359873e9ef/tests/test_nam/test_models/test_exportable.py#L114

...etc

**Comment by vossenv** [comment]
@Rodolfo-S I believe that's correct, unless I'm missing something deeper wrt pydantic
