### ISSUE TITLE
[BUG] pip's dependency resolver

### ISSUE THREAD

**Issue by giacomopas** [sdatkinson/neural-amp-modeler#434]
![Screenshot_1](https://github.com/sdatkinson/neural-amp-modeler/assets/172249461/635256b4-8f7b-4681-a4b7-183284ecd361)

Local Installation of the trainer, following original video (https://www.youtube.com/watch?v=DFWVvJx1Cfs).
I already installed anaconda and trainer on other desktop pcs with no issues.

**This time I got this errore message when installing NAM**:
_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-cloud-auth 0.1.4 requires pydantic<2.0, but you have pydantic 2.7.3 which is incompatible._

OS: Windows 11

Does this affects the training or is it something ignorable?

**Comment by sdatkinson** [comment]
You can ignore it--`anaconda-cloud-auth`isn't used by NAM--it's just there in the `base` environment that Anaconda ships with (which is getting bloated, it seems. I'd like to find a better solution and stop depending on it.)

Lmk if something does go wrong; otherwise, feel free to close this Issue if you're happy.
