### ISSUE TITLE
[FEATURE] OpenVINO port

### ISSUE THREAD

**Issue by MarcoRavich** [sdatkinson/neural-amp-modeler#455]
Hi there, thanks for this great project !

To let more people - who do not own an NVIDIA GPU (like me) - to be active in the "capture/learning community", it would be cool to favour @Intel [*PUs](https://docs.openvino.ai/2022.3/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html) owners' join.

Although I am not a dev, it shouldn't be extremely difficoult to "convert" the model from PyTorch to @openvinotoolkit according to this document: [Converting a PyTorch Model](https://docs.openvino.ai/2024/openvino-workflow/model-preparation/convert-model-to-ir.html)

In any case I believe that [OpenVINO™](https://github.com/openvinotoolkit/openvino)'s contributors may help (as @RyanMetcalfeInt8 and @rdower did for [these plugins](https://github.com/intel/openvino-plugins-ai-audacity)) if needed: 
https://github.com/openvinotoolkit/openvino/graphs/contributors

Thanks in advance !

**Comment by sdatkinson** [comment]
Hi.

I'm going to be keeping the trainer PyTorch-based since it's, by far, the most completely-developed, well-supported deep learning framework out there.

I'm not familiar with OpenVINO, but it looks like it's for making rpedictions with already-trained models? That's out of scope for this repo, but as far as running the models, there's [`NeuralAmpModelerCore`](https://github.com/sdatkinson/NeuralAmpModelerCore) with a library for building applications that run the models in real time (like audio plug-ins), and [`NeuralAmpModelerPlugin`](https://github.com/sdatkinson/NeuralAmpModelerPlugin), which demonstrates how to use it. Critically, these both use `.nam` files to store the models, which is independent of PyTorch.
