### ISSUE TITLE
[FEATURE] Converter from NAM profile to AM2 (M-vave, G-tank and others)

### ISSUE THREAD

**Issue by StanislawKarnacky** [sdatkinson/neural-amp-modeler#466]
I have accumulated many NAM profiles, and it would be fantastic if I could use them with affordable pedals like G-tank and others, but extension of their profiles is different (.am2)

**Comment by sdatkinson** [comment]
It's more than that--they're closed-source, which unfortunately makes their ecosystem a walled garden that I can't make NAM a part of.

It's a little like asking me to help you load your own impulse responses onto the [POD HD](https://shop-us.line6.com/legacy-gear/pod-hd-pro/)--since they used a proprietary algorithm, it's not interoperable. Or how Fractal provides Cab Lab to convert IRs to their format--since they defined their own .syx format, they're the only ones who can add support for impulse responses saved as WAVE files.

You could ask M-VAVE (or any other company) to support NAM, but other than that there's nothing I can do from my side unfortunately.
