### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by binky100** [sdatkinson/neural-amp-modeler#519]
Hello,

I'm facing issues with the local Neural Amp Modeler trainer on both Windows (MSI PC with GTX 1650) and macOS (MacBook Pro M3 Pro).

Problem:

When I attempt to start the local trainer, it plots the latency graph but then hangs indefinitely. The trainer only resumes after I manually close the latency plot, but unfortunately, it switches to CPU mode instead of utilizing the GPU. This significantly slows down the training process.

Specifics:

    Windows: MSI PC with GTX 1650
    macOS: MacBook Pro with M3 Pro Processor

I've followed the installation and setup instructions, and all required packages (PyTorch, CUDA, etc.) are installed and working correctly.

Request:

I kindly request your assistance in resolving this issue. Any guidance on troubleshooting the GPU utilization and trainer behavior would be greatly appreciated.

Thank you for your time and support.
![PC NAM Local Trainer Stuck](https://github.com/user-attachments/assets/62e16d4b-f64c-40c6-b15d-f5dc8d337ea0)
![CPU fallback error](https://github.com/user-attachments/assets/0314cd4f-bb0b-4209-b1fb-2af5e2b29bc4)
![PC GPU](https://github.com/user-attachments/assets/cf9debe0-8eff-40d9-a642-1bbc8a922155)

**Comment by sdatkinson** [comment]
> it plots the latency graph but then hangs indefinitely. The trainer only resumes after I manually close the latency plot

As you said, close the plot to continue.

As for the MRSTFT, this is being tracked here: https://github.com/sdatkinson/neural-amp-modeler/issues/453. Unfortunately, it's a low-level gap that exists right now on MPS. +1 the links on #453 to let the devs know that this is important to you, but it's out of scope for NAM.

As for Windows using GPU, I don't have the information needed to understand what you did. I don't provide any instructions that ask you to install CUDA. My instructions are here: https://neural-amp-modeler.readthedocs.io/en/latest/installation.html. Please have a look at that and follow those instructions.

---

Closing this; if you still are having trouble, please open a new Issue and follow the template so that I have all the info I need to help. Thanks!

**Comment by binky100** [comment]
I followed your instructions on the website you just listed and Im still getting my gpu not being used and the trainer falls back to the CPU. From all the research I have done the Nvidia GTX 1650 should work but isnt. What can I do to figure out why the nam local trainer isnt working and keeps using the CPU?

**Comment by fps** [comment]
Hey, installing pytorch from conda on windows failed for me as well, since the build didn't have CUDA support. I used PIP in the end. Though I still created the environmen initially with conda:

```
create -n nam python=3.13.4
conda activate nam
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126```
pip install neural-amp-modeler
pip3 install standard-imghdr
```

I think `standard-imghdr` was required for tensorboard. Good luck!
