### ISSUE TITLE
How to set properly "config_data_single_pair.json" samples + delay?

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#91]
How do I know what delay I need to set? Is there an easy way to find out the sample numbers?

`{
    "train": {
        "start": null,
        "stop": 9124249,
        "ny": 1024
    },
    "validation": {
        "start": 9124249,
        "stop": null,
        "ny": null
    },
    "common": {
        "x_path": "/Users/.../bin/train/outputs/v1_1_1.wav",
        "y_path": "/Users/.../bin/train/outputs/output.wav",
        "delay": 0
    }
}`

**Comment by ServusJon** [comment]
Also what does "ny" stand for?

**Comment by sdatkinson** [comment]
> How do I know what delay I need to set?
Set it according to how many samples the output lags the input by. For example, look at this comparison of the input & output:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/12240186/219884861-1aa01cc3-b38a-43b8-9e8b-6c15384eab53.png">

Based on my eyeballing it, the output first seems to move around sample 12029 (where I've put the vertical ruler). The input that cause this starts at sample 12000. To align them, I would set `"delay": 29` in the config.

_However_, if you make a mistake and _over_-correct, then the output would happen _before_ the input that caused it, which would be...hard to predict 😅 So, putting in a little safety factor (say, subtract a few samples) can help make sure you aren't trying to "predict the future" because you keyed in on a blip in the noise instead of a real response to the input.  In `easy_colab.ipynb`, See [the `safety_factor` in nam/train/colab.py](https://github.com/sdatkinson/neural-amp-modeler/blob/f8509336e28eb292557c9abb8af019cb31892543/nam/train/colab.py#L101).

This is probably the "easiest" way to do it if you aren't using "easy mode".

> Also what does "ny" stand for?

This is the number of samples in a single output "datum" that the model is asked to predict at once. See [the definition of `Dataset._ny`](https://github.com/sdatkinson/neural-amp-modeler/blob/f8509336e28eb292557c9abb8af019cb31892543/nam/data.py#L222) and [how it's used to get data](https://github.com/sdatkinson/neural-amp-modeler/blob/f8509336e28eb292557c9abb8af019cb31892543/nam/data.py#L234).
